apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment-alertmanager
  namespace: monitoring
  labels:
    name: prometheus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-deployment-alertmanager
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path:   /metrics
        prometheus.io/port:   "9093"
      labels:
        app.kubernetes.io/name: prometheus-deployment-alertmanager
    spec:
      containers:
        - name: prometheus-deployment-alertmanager
          image: prom/alertmanager:v0.19.0
          args:
            - "--config.file=/etc/alertmanager/alertmanager.yml"
            - "--web.external-url=http://192.168.100.10:30000/alertmanager/"
            - "--web.route-prefix=/"
          ports:
            - name: http
              containerPort: 9093
              protocol: TCP
          volumeMounts:
            - name: cfg
              mountPath: /etc/alertmanager/
          resources:
            requests:
              cpu: "64m"
              memory: "64Mi"
            limits:
              cpu: "128m" 
              memory: "256Mi"
      volumes:
        - name: cfg
          configMap:
            defaultMode: 420
            name: prometheus-deployment-cm-alertmanager-conf
