apiVersion: v1
kind: Service
metadata:
  name: prometheus-deployment-alertmanager
  namespace: monitoring
  labels:
    name: prometheus-deployment
  annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path:   /metrics
      prometheus.io/port:   "9093"
spec:
  type: NodePort
  ports:
    - port: 9093
      name: http
      protocol: TCP
      nodePort: 31001
  selector:
    app.kubernetes.io/name: prometheus-deployment-alertmanager
