apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-prometheus-metrics
  namespace: default
  labels:
    app: nginx-prometheus-metrics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-prometheus-metrics
  template:
    metadata:
      annotations:
        prometheus.io/port: "9527"
        prometheus.io/scrape: "true"
      labels:
        app: nginx-prometheus-metrics
    spec:
      containers:
      - name: nginx-prometheus-metrics
        image: sophos/nginx-prometheus-metrics
        ports:
        - containerPort: 80
        - containerPort: 9527
        - containerPort: 1314
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
      #####second container for example#####
      # - name: tomcat
      #   image: tomcat
      #   ports:
      #   - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata: 
  name:  nginx-prometheus-metrics
spec:
  type: NodePort
  selector:   
    app:  nginx-prometheus-metrics
  ports: 
  - name: http
    port: 80
    targetPort: 80
    nodePort: 32000
    protocol: TCP
  - name: metrics
    port: 9527
    targetPort: 9527
    nodePort: 32001
    protocol: TCP
  - name: test
    port: 1314
    targetPort: 1314
    nodePort: 32002
    protocol: TCP