apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: trickster
  name: trickster
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: trickster
      name: trickster
    spec:
      containers:
        - name: trickster
          image: tricksterio/trickster:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: cfg-volume
              mountPath: /etc/trickster
          resources:
            requests:
              cpu: "64m"
              memory: "64Mi"
            limits:
              cpu: "128m" 
              memory: "256Mi"
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: cfg-volume
          configMap:
            name: trickster-conf
            items:
              - key: trickster-conf
                path: trickster.conf

